AllCops: 
  NewCops: enable 

# The following rules are ignored because for this project they generate more noise than value

# Rspec can yield long describe blocks
Metrics/BlockLength:
  Enabled: false

# Page-Object classes tend to exceed rule length
Metrics/ClassLength:
  Enabled: false

# Page-Object classes may exceed rule length
Metrics/MethodLength:
  Enabled: false

# Identifiers may exceed rule length
Metrics/ModuleLength:
  Enabled: false

# Naming is hard, but we aspire to do it well
Style/Documentation: 
  Enabled: false
