# frozen_string_literal: true

module Users
  CC_USER = ENV['CC_USER_EMAIL']
  ORG_PRINCETON = ENV['ORG_PRINCETON_EMAIL']
  ORG_YALE = ENV['ORG_YALE_EMAIL']
  ORG_COLUMBIA = ENV['ORG_COLUMBIA_EMAIL']
  ORG_NEWYORK = ENV['ORG_NEWYORK_EMAIL']
  DEFAULT_PASSWORD = ENV['DEFAULT_PASSWORD']
end

